#!/bin/sh
$ran=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 5)
cat ~/git-token
git pull
git add .
git commit -m "update$ran"
git push
echo "\033[33m\033[1m\033[4m<\033[0m\033[29m\033[1m\033[4m  Attempt to GitPush finish \033[0m\033[33m\033[1m\033[4m>\033[0m"
