#!/bin/sh
while true
do
    echo "\033[31m||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\033[00m"
    echo "\033[36m_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'_'\033[00m"
    echo "\n"
    echo "\033[36mExternal IP : (if VPN is actived , it would be you VPN IP):\n\033[00m""\033[37m\033[31m|||||||||||||||||||||\n||\033[00m[ $(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//') ]\033[31m||\n|||||||||||||||||||||\033[00m\033[00m" "\033[36m\n\nSOCKS.5-TORPROXY: (If the case is empty , you are not Connected)\n\033[00m \033[37m[ $(~/.___/script/torservicecheck) ]\033[00m"
    echo "\n"
    sleep 4s
done
