#!/bin/sh
variable='*'
if [ $# > 1 ]
 then
echo $*
echo "\033[32;1;7m\tFichier trouvés\t\n\tOpération en cours...\t\033[0m"	
	sed -i.bak '1,12 d' $*
	echo "Vérification des bannières :\n"
	grep -E -i '/*' $*
	rm -rf *.bak 1 
 else
set b
echo "Syntaxe : $0 et Quel type de fichier vous voulez, ex: *.c"
fi


