#!/bin/bash
brew services start tor
sudo networksetup -setsocksfirewallproxy "Wi-Fi" 127.0.0.1 9050
sudo networksetup -setsocksfirewallproxy "iPhone USB" 127.0.0.1 9050
sudo networksetup -setsocksfirewallproxy "Ethernet" 127.0.0.1 9050
curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'
